import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Button from "./Button";
export function PageContainer({children,className=""}){return _jsx("div",{className:`page-container ${className}`.trim(),children})}
export function PageHeader({title,description,eyebrow="Controle Operacional",actions,breadcrumb,className=""}){return _jsxs("header",{className:`page-header-system ${className}`.trim(),children:[_jsxs("div",{className:"page-header-system__copy",children:[breadcrumb?_jsx("div",{className:"page-breadcrumb",children:breadcrumb}):null,_jsx("p",{className:"page-header-system__eyebrow",children:eyebrow}),_jsx("h1",{children:title}),description?_jsx("p",{children:description}):null]}),actions?_jsx("div",{className:"page-header-system__actions",children:actions}):null]})}
export function SectionCard({children,className="",as="section"}){const Element=as;return _jsx(Element,{className:`section-card-system ${className}`.trim(),children})}
export function MetricCard({label,value,helper,tone="default",className=""}){return _jsxs("article",{className:`metric-card-system metric-card-system--${tone} ${className}`.trim(),children:[_jsx("span",{children:label}),_jsx("strong",{children:value}),helper?_jsx("small",{children:helper}):null]})}
export function StatusBadge({children,tone="neutral",className=""}){return _jsx("span",{className:`status-badge-system status-badge-system--${tone} ${className}`.trim(),children})}
export function ResponsiveGrid({children,columns=2,className=""}){return _jsx("div",{className:`responsive-grid responsive-grid--${columns} ${className}`.trim(),children})}
export function FormField({label,helper,error,full=false,children,className=""}){return _jsxs("label",{className:`form-field-system ${full?"form-field-system--full":""} ${className}`.trim(),children:[_jsx("span",{children:label}),children,error?_jsx("small",{className:"form-field-system__error",children:error}):helper?_jsx("small",{children:helper}):null]})}
export function SearchField({label="Buscar",className="",...props}){return _jsxs("label",{className:`search-field-system ${className}`.trim(),children:[_jsx("span",{className:"sr-only",children:label}),_jsx("i",{"aria-hidden":"true",children:"⌕"}),_jsx("input",{"aria-label":label,...props})]})}
export function DataTable({children,className="",label="Dados"}){return _jsx("div",{className:`data-table-system ${className}`.trim(),role:"region","aria-label":label,tabIndex:0,children:_jsx("table",{children})})}
export function MobileDataCard({children,className=""}){return _jsx("article",{className:`mobile-data-card ${className}`.trim(),children})}
export function EmptyState({title="Nenhum registro encontrado",description,action,className=""}){return _jsxs("div",{className:`empty-state-system ${className}`.trim(),children:[_jsx("span",{"aria-hidden":"true",children:"◇"}),_jsx("strong",{children:title}),description?_jsx("p",{children:description}):null,action]})}
export function LoadingState({label="Carregando...",className=""}){return _jsxs("div",{className:`loading-state-system ${className}`.trim(),role:"status",children:[_jsx("i",{"aria-hidden":"true"}),_jsx("span",{children:label})]})}
export function InfoBanner({children,tone="info",className=""}){return _jsx("div",{className:`info-banner-system info-banner-system--${tone} ${className}`.trim(),role:tone==="danger"?"alert":"status",children})}
export function ActionBar({children,className=""}){return _jsx("div",{className:`action-bar-system ${className}`.trim(),children})}
export function ConfirmModal({open,title,description,confirmLabel="Confirmar",cancelLabel="Cancelar",danger=false,onConfirm,onCancel}){if(!open)return null;return _jsx("div",{className:"modal-system-backdrop",role:"presentation",onMouseDown:event=>event.target===event.currentTarget&&onCancel?.(),children:_jsxs("section",{className:"confirm-modal-system",role:"dialog","aria-modal":"true","aria-labelledby":"confirm-modal-title",children:[_jsx("h2",{id:"confirm-modal-title",children:title}),description?_jsx("p",{children:description}):null,_jsxs("div",{children:[_jsx(Button,{variant:"secondary",onClick:onCancel,children:cancelLabel}),_jsx(Button,{variant:danger?"danger":"primary",onClick:onConfirm,children:confirmLabel})]})]})})}
