import { Router } from "express";
import { prisma } from "../../lib/prisma";
import { requireAuth, type AuthenticatedRequest } from "../../middleware/auth";
import { AppError } from "../../middleware/errorHandler";
import { requirePermission } from "../../middleware/permissions";
import { allocateFleet, getFleetHistory, getFleetLocation, getOperationalMap, moveFleet, releaseFleet } from "./yard.service";

export const yardRoutes = Router();
const clean = (value: unknown, max = 500) => typeof value === "string" ? value.replace(/[\u0000-\u001f\u007f]/g, " ").trim().slice(0, max) : "";
function branch(value: unknown) { const result = (clean(value, 40) || "PAULINIA").toUpperCase(); if (!/^[A-Z0-9_-]{2,40}$/.test(result)) throw new AppError("Filial inválida.", 400, "BAD_REQUEST"); return result; }
function positive(value: unknown, fallback: number, max = 100) { const number = Number(value); return Number.isInteger(number) && number > 0 ? Math.min(number, max) : fallback; }
function user(req: AuthenticatedRequest) { if (!req.user) throw new AppError("Usuário não autenticado.", 401, "UNAUTHORIZED"); return req.user; }
function allocationBody(req: any) { const fleetId = clean(req.body?.fleetId, 100), areaId = clean(req.body?.areaId, 100), note = clean(req.body?.note); if (!fleetId || !areaId) throw new AppError("Frota e área são obrigatórias.", 400, "BAD_REQUEST"); return { fleetId, areaId, note: note || null }; }

yardRoutes.use(requireAuth);
yardRoutes.get("/dashboard", requirePermission("yard:view"), async (req, res, next) => { try { return res.json(await getOperationalMap(branch(req.query.branch))); } catch (error) { return next(error); } });
yardRoutes.get("/fleets", requirePermission("yard:search"), async (req, res, next) => { try { const search = clean(req.query.search, 100); const fleets = await prisma.frota.findMany({ where: search ? { OR: [{ numeroFrota: { contains: search, mode: "insensitive" } }, { placa: { contains: search, mode: "insensitive" } }, { tipoEquipamento: { contains: search, mode: "insensitive" } }] } : undefined, orderBy: { numeroFrota: "asc" }, take: positive(req.query.limit, 500, 1000) }); return res.json({ fleets }); } catch (error) { return next(error); } });
yardRoutes.get("/fleets/:fleetId/history", requirePermission("yard:history"), async (req, res, next) => { try { return res.json(await getFleetHistory(clean(req.params.fleetId, 100), positive(req.query.page, 1), positive(req.query.limit, 20))); } catch (error) { return next(error); } });
yardRoutes.get("/fleets/:fleetId", requirePermission("yard:view"), async (req, res, next) => { try { return res.json(await getFleetLocation(clean(req.params.fleetId, 100))); } catch (error) { return next(error); } });
yardRoutes.post("/allocations", requirePermission("yard:update"), async (req, res, next) => { try { return res.status(201).json({ allocation: await allocateFleet({ ...allocationBody(req), userId: user(req as AuthenticatedRequest).id }) }); } catch (error) { return next(error); } });
yardRoutes.post("/allocations/move", requirePermission("yard:update"), async (req, res, next) => { try { return res.json({ allocation: await moveFleet({ ...allocationBody(req), userId: user(req as AuthenticatedRequest).id }) }); } catch (error) { return next(error); } });
yardRoutes.post("/allocations/:id/release", requirePermission("yard:update"), async (req, res, next) => { try { return res.json({ allocation: await releaseFleet({ allocationId: clean(req.params.id, 100), note: clean(req.body?.note) || null, userId: user(req as AuthenticatedRequest).id }) }); } catch (error) { return next(error); } });

yardRoutes.post("/patios", requirePermission("yard:areas-manage"), async (req, res, next) => { try { const nome = clean(req.body?.nome, 100), ordem = Number(req.body?.ordem ?? 0); if (!nome || !Number.isInteger(ordem)) throw new AppError("Nome e ordem válida são obrigatórios.", 400, "BAD_REQUEST"); return res.status(201).json({ patio: await prisma.patio.create({ data: { branch: branch(req.body?.branch), nome, ordem } }) }); } catch (error) { return next(error); } });
yardRoutes.post("/areas", requirePermission("yard:areas-manage"), async (req, res, next) => { try { const nome = clean(req.body?.nome, 100), capacidade = Number(req.body?.capacidade), x = Number(req.body?.x), y = Number(req.body?.y), cor = clean(req.body?.cor, 7) || "#22c55e"; if (!nome || !Number.isInteger(capacidade) || capacidade < 1 || !Number.isFinite(x) || x < 0 || x > 1 || !Number.isFinite(y) || y < 0 || y > 1 || !/^#[0-9a-f]{6}$/i.test(cor)) throw new AppError("Dados da área inválidos.", 400, "BAD_REQUEST"); return res.status(201).json({ area: await prisma.patioArea.create({ data: { patioId: clean(req.body?.patioId, 100), nome, capacidade, x, y, cor, ordem: Number(req.body?.ordem) || 0 } }) }); } catch (error) { return next(error); } });
yardRoutes.patch("/areas/:id", requirePermission("yard:areas-manage"), async (req, res, next) => { try { const data: any = {}; for (const key of ["nome", "cor"] as const) if (req.body?.[key] !== undefined) data[key] = clean(req.body[key], key === "cor" ? 7 : 100); for (const key of ["capacidade", "ordem", "x", "y"] as const) if (req.body?.[key] !== undefined) data[key] = Number(req.body[key]); if (req.body?.ativo !== undefined) data.ativo = req.body.ativo === true; if (data.nome !== undefined && !data.nome) throw new AppError("Nome da área é obrigatório.", 400, "BAD_REQUEST"); if (data.capacidade !== undefined || data.ativo === false) { const occupied = await prisma.patioAllocation.count({ where: { areaId: req.params.id, releasedAt: null } }); if (data.ativo === false && occupied > 0) throw new AppError("Libere as frotas antes de inativar a área.", 409, "AREA_HAS_ALLOCATIONS"); if (data.capacidade !== undefined && (!Number.isInteger(data.capacidade) || data.capacidade < Math.max(1, occupied))) throw new AppError("A capacidade não pode ser menor que a ocupação atual.", 409, "CAPACITY_BELOW_OCCUPANCY"); } if ((data.ordem !== undefined && !Number.isInteger(data.ordem)) || (data.x !== undefined && (!Number.isFinite(data.x) || data.x < 0 || data.x > 1)) || (data.y !== undefined && (!Number.isFinite(data.y) || data.y < 0 || data.y > 1)) || (data.cor !== undefined && !/^#[0-9a-f]{6}$/i.test(data.cor))) throw new AppError("Dados da área inválidos.", 400, "BAD_REQUEST"); return res.json({ area: await prisma.patioArea.update({ where: { id: req.params.id }, data }) }); } catch (error) { return next(error); } });
