import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { autocompleteProducts, createInspecao, getFrotaByNumero, listCollaborators, searchFrotas, uploadFotos } from "../api";
import AppLayout from "../components/layout/AppLayout";
import CriticalPointForm from "../components/inspecao/CriticalPointForm";
import Button from "../components/ui/Button";
import { getAuthUser, logout } from "../utils/auth";

const DRAFT_KEY = "nova-inspecao:draft:v2";
const STEPS = ["Dados iniciais", "Checklist", "Evidências", "Revisão e envio"];
const PROCEDURES = { WASH_ONLY: "Lavagem sem vapor", STEAM_ONLY: "Somente vapor", WASH_AND_STEAM: "Lavagem + vapor", NO_WASH_REQUIRED: "Não necessita lavagem", NOT_DEFINED: "Não definido" };
const LEVELS = { LOW: "Baixo", MEDIUM: "Médio", HIGH: "Alto" };
const CHECKLIST_BASE = [
  ["boca-visita", "Boca de visita e tampa", "Boca de visita", "Mancha"], ["valvulas", "Válvulas e drenos", "Válvulas e drenos", "Resquício de produto"],
  ["interior", "Interior do tanque", "Parte interna", "Resquício de produto"], ["quebra-ondas", "Quebra-ondas", "Quebra-ondas", "Ferrugem"],
  ["soldas", "Soldas", "Soldas", "Ferrugem"], ["fundo", "Fundo e chapa", "Fundo e chapa", "Mancha"], ["odor", "Odor ou resíduo aparente", "Geral", "Resquício de produto"]
];
const CATEGORIAS = ["Ferrugem", "Mancha", "Amarelamento", "Odor", "Produto residual", "Válvula contaminada", "Outro", "Resquício de produto", "Fuligem"];
const SEVERIDADES = ["LEVE", "MEDIA", "GRAVE"];
function initialChecklist(){return CHECKLIST_BASE.map(([id,label,localizacao,categoria])=>({id,label,localizacao,categoria,status:"PENDENTE",severidade:"LEVE",descricao:"",procedimentoRecomendado:""}))}
function initialValues(name){return{numeroFrota:"",placa:"",tipoEquipamento:"",dataInspecao:new Date().toISOString().slice(0,16),tipoInspecao:"ANTES_LAVAGEM",status:"COM_OBSERVACAO",colaboradorId:"",resultadoPosLavagem:"",motivoNaoConformidade:"",nomeInspetor:name,observacoesGerais:""}}
function loadDraft(name){try{const draft=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null");return draft?{values:{...initialValues(name),...draft.values,nomeInspetor:name},checklist:draft.checklist||initialChecklist(),pontos:(draft.pontos||[]).map(p=>({...p,files:[]})),product:draft.product||null}:null}catch{return null}}
function checklistPoints(items){return items.filter(i=>i.status==="ATENCAO").map(i=>({categoria:i.categoria,localizacao:i.localizacao,descricao:i.descricao.trim()||`Apontamento no checklist: ${i.label}.`,severidade:i.severidade,procedimentoRecomendado:i.procedimentoRecomendado.trim()||"Avaliar, limpar e reinspecionar antes da liberação.",files:[]}))}
function checklistNote(items){const ok=items.filter(i=>i.status==="OK").length,attention=items.filter(i=>i.status==="ATENCAO");return attention.length?`Checklist fixo: ${ok} itens OK, ${attention.length} com atenção. Atenção em: ${attention.map(i=>i.label).join(", ")}.`:`Checklist fixo: ${ok} itens OK, sem apontamento.`}

export default function NovaInspecaoPage(){
  const navigate=useNavigate(),authUser=getAuthUser(),inspectorName=authUser?.fullName?.trim()||authUser?.name||"";const restored=useMemo(()=>loadDraft(inspectorName),[]);
  const[step,setStep]=useState(0),[values,setValues]=useState(restored?.values||initialValues(inspectorName)),[checklist,setChecklist]=useState(restored?.checklist||initialChecklist()),[pontos,setPontos]=useState(restored?.pontos||[]);
  const[selectedProduct,setSelectedProduct]=useState(restored?.product||null),[productQuery,setProductQuery]=useState(restored?.product?.name||""),[productOptions,setProductOptions]=useState([]),[productLoading,setProductLoading]=useState(false),[productDetails,setProductDetails]=useState(false);
  const[frota,setFrota]=useState(null),[fleetState,setFleetState]=useState("idle"),[collaborators,setCollaborators]=useState([]),[menuOpen,setMenuOpen]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(restored?"Rascunho recuperado.":""),[error,setError]=useState("");
  useEffect(()=>{listCollaborators().then(r=>setCollaborators(r.colaboradores.filter(c=>c.ativo))).catch(()=>setCollaborators([]))},[]);
  useEffect(()=>{if(productQuery.trim().length<2||selectedProduct?.name===productQuery){setProductOptions([]);setProductLoading(false);return}setProductLoading(true);const timer=setTimeout(()=>autocompleteProducts(productQuery).then(r=>setProductOptions(r.products)).catch(()=>setProductOptions([])).finally(()=>setProductLoading(false)),250);return()=>clearTimeout(timer)},[productQuery,selectedProduct]);
  useEffect(()=>{const number=values.numeroFrota.trim();if(!number){setFrota(null);setFleetState("idle");return}setFleetState("loading");const timer=setTimeout(async()=>{try{let found=(await getFrotaByNumero(number)).frota;if(!found){const result=await searchFrotas(number);if(result.frotas.length===1)found=result.frotas[0]}setFrota(found);setFleetState(found?"found":"missing");if(found)setValues(v=>({...v,numeroFrota:found.numeroFrota,placa:found.placa||"",tipoEquipamento:found.tipoEquipamento||""}))}catch{setFrota(null);setFleetState("offline")}},300);return()=>clearTimeout(timer)},[values.numeroFrota]);
  useEffect(()=>{const timer=setTimeout(()=>{const cleanPoints=pontos.map(({files,...p})=>p);localStorage.setItem(DRAFT_KEY,JSON.stringify({values,checklist,pontos:cleanPoints,product:selectedProduct,updatedAt:new Date().toISOString()}))},400);return()=>clearTimeout(timer)},[values,checklist,pontos,selectedProduct]);
  function change(field,value){setValues(v=>{if(field==="placa")value=value.toUpperCase().replace(/\s+/g,"").slice(0,7);if(field==="tipoInspecao"&&value==="ANTES_LAVAGEM")return{...v,tipoInspecao:value,colaboradorId:"",resultadoPosLavagem:"",motivoNaoConformidade:""};if(field==="resultadoPosLavagem")return{...v,resultadoPosLavagem:value,motivoNaoConformidade:value==="REPROVADO"?v.motivoNaoConformidade:""};return{...v,[field]:value}})}
  function updateChecklist(id,field,value){setChecklist(c=>c.map(i=>i.id===id?{...i,[field]:value}:i))}
  function validateData(){if(!selectedProduct)return"Selecione a última carga.";if(!values.numeroFrota.trim())return"Informe o número da frota.";if(!values.placa.trim())return"Informe a placa.";if(!values.tipoEquipamento)return"Selecione o tipo de tanque.";if(!values.dataInspecao)return"Informe a data da inspeção.";return""}
  function goNext(){const validation=step===0?validateData():"";if(validation){setError(validation);return}setError("");setStep(s=>Math.min(3,s+1));window.scrollTo({top:0,behavior:"smooth"})}
  function saveDraft(){localStorage.setItem(DRAFT_KEY,JSON.stringify({values,checklist,pontos:pontos.map(({files,...p})=>p),product:selectedProduct,updatedAt:new Date().toISOString()}));setNotice("Rascunho salvo neste dispositivo.");setTimeout(()=>setNotice(""),2500)}
  async function submit(){const validation=validateData();if(validation){setError(validation);setStep(0);return}if(values.tipoInspecao==="APOS_LAVAGEM"&&(!values.colaboradorId||!values.resultadoPosLavagem)){setError("Informe colaborador e resultado da pós-lavagem.");return}if(values.resultadoPosLavagem==="REPROVADO"&&!values.motivoNaoConformidade){setError("Informe o motivo da não conformidade.");return}setSaving(true);setError("");try{const allPoints=[...checklistPoints(checklist),...pontos],observations=[values.observacoesGerais.trim(),checklistNote(checklist)].filter(Boolean).join("\n\n"),isPost=values.tipoInspecao==="APOS_LAVAGEM";const response=await createInspecao({productId:selectedProduct.id,frotaId:frota?.id??values.numeroFrota,numeroFrota:values.numeroFrota,placa:values.placa,tipoEquipamento:values.tipoEquipamento,dataInspecao:new Date(values.dataInspecao).toISOString(),tipoInspecao:values.tipoInspecao,status:isPost&&values.resultadoPosLavagem?values.resultadoPosLavagem:values.status,colaboradorId:isPost?values.colaboradorId:null,resultadoPosLavagem:isPost?values.resultadoPosLavagem:null,motivoNaoConformidade:isPost&&values.resultadoPosLavagem==="REPROVADO"?values.motivoNaoConformidade:null,observacoesGerais:observations||null,pontosCriticos:allPoints.map(({files,...point})=>point)});const created=response.inspecao.pontosCriticos||[],uploads=allPoints.flatMap((point,index)=>(point.files||[]).map(file=>({file,pontoCriticoId:created[index]?.id||""})));if(uploads.length){const form=new FormData();uploads.forEach(item=>{form.append("files[]",item.file);form.append("pontoCriticoId",item.pontoCriticoId)});await uploadFotos(response.inspecao.id,form)}localStorage.removeItem(DRAFT_KEY);navigate(`/inspecao/${response.inspecao.id}`)}catch(e){setError(e.message||"Falha ao salvar inspeção.")}finally{setSaving(false)}}
  function handleLogout(){if(window.confirm("Deseja sair do sistema?")){logout();navigate("/login",{replace:true})}}
  const addPoint=()=>setPontos(p=>[...p,{categoria:"",localizacao:"",descricao:"",severidade:"LEVE",procedimentoRecomendado:"",files:[]}]);
  return <AppLayout className="inspection-flow-layout"><div className="inspection-flow">
    <header className="inspection-flow__header"><button type="button" className="icon-button" onClick={()=>navigate(-1)} aria-label="Voltar">←</button><div><span>Nova inspeção</span><small>Etapa {step+1} de 4 · {STEPS[step]}</small></div><button type="button" className="icon-button" onClick={()=>setMenuOpen(v=>!v)} aria-label="Mais opções" aria-expanded={menuOpen}>⋮</button>{menuOpen?<div className="inspection-flow__menu"><button onClick={()=>navigate("/perfil")}>Perfil</button><button onClick={saveDraft}>Salvar rascunho</button><button onClick={handleLogout}>Deslogar</button></div>:null}</header>
    <nav className="inspection-stepper" aria-label="Etapas da inspeção">{STEPS.map((label,index)=><button type="button" key={label} className={index===step?"is-current":index<step?"is-complete":""} onClick={()=>index<step&&setStep(index)}><i>{index<step?"✓":index+1}</i><span>{label}</span></button>)}</nav>
    {notice?<p className="notice notice--success" role="status">{notice}</p>:null}{error?<p className="notice notice--error" role="alert">{error}</p>:null}
    <div className="inspection-flow__layout"><main className="inspection-stage">
      {step===0?<section aria-labelledby="step-data"><div className="inspection-stage__title"><span>1</span><div><h1 id="step-data">Dados iniciais</h1><p>Identifique a carga e a frota.</p></div></div>
        <div className="inspection-fields"><label className="inspection-field inspection-field--wide"><span>Última carga</span><div className="inspection-autocomplete"><input value={productQuery} onChange={e=>{setProductQuery(e.target.value);if(e.target.value!==selectedProduct?.name)setSelectedProduct(null)}} placeholder="Buscar produto ou ONU" autoComplete="off" aria-autocomplete="list"/>{productQuery?<button type="button" onClick={()=>{setProductQuery("");setSelectedProduct(null)}} aria-label="Limpar produto">×</button>:null}</div>{productLoading?<small>Buscando produtos...</small>:null}{productOptions.length?<div className="inspection-suggestions" role="listbox">{productOptions.map(product=><button type="button" key={product.id} onClick={()=>{setSelectedProduct(product);setProductQuery(product.name);setProductOptions([])}}><strong>{product.name}</strong><span>{product.unNumber?`ONU ${product.unNumber} · `:""}{product.family?.name||"Sem família"}</span></button>)}</div>:null}</label>
          {selectedProduct?<div className="compact-product inspection-field--wide"><div><strong>{selectedProduct.name}</strong><span>{PROCEDURES[selectedProduct.washingProcedure||"NOT_DEFINED"]} · Risco {LEVELS[selectedProduct.riskLevel]||"não informado"} · Dificuldade {LEVELS[selectedProduct.washDifficulty]||"não informada"}</span></div><button type="button" onClick={()=>setProductDetails(true)}>Ver detalhes</button></div>:null}
          <label className="inspection-field"><span>Número da frota</span><input inputMode="numeric" value={values.numeroFrota} onChange={e=>change("numeroFrota",e.target.value.replace(/\D/g,""))} placeholder="Ex.: 5832"/>{fleetState==="loading"?<small>Buscando frota...</small>:null}</label>
          <label className="inspection-field"><span>Placa</span><input value={values.placa} onChange={e=>change("placa",e.target.value)} placeholder="ABC1D23" autoCapitalize="characters"/></label>
          {fleetState==="found"?<div className="fleet-summary inspection-field--wide"><span>✓</span><div><strong>Frota {frota.numeroFrota}</strong><small>{frota.placa} · {frota.tipoEquipamento}</small></div></div>:fleetState==="missing"?<div className="fleet-summary fleet-summary--warning inspection-field--wide"><span>!</span><div><strong>Frota não encontrada</strong><small>Cadastre os dados manualmente abaixo.</small></div></div>:fleetState==="offline"?<p className="inline-state inspection-field--wide">Conexão instável. Você pode continuar preenchendo.</p>:null}
          <label className="inspection-field"><span>Tipo de tanque</span><select value={values.tipoEquipamento} onChange={e=>change("tipoEquipamento",e.target.value)}><option value="">Selecione</option>{["Tanque inox","Tanque carbono","Carreta tanque","Bitrem tanque","Isotank","Outro"].map(v=><option key={v}>{v}</option>)}</select>{values.tipoEquipamento?<small>Tipo selecionado com sucesso.</small>:null}</label>
          <label className="inspection-field"><span>Data da inspeção</span><input type="datetime-local" value={values.dataInspecao} onChange={e=>change("dataInspecao",e.target.value)}/></label>
          <label className="inspection-field"><span>Tipo da inspeção</span><select value={values.tipoInspecao} onChange={e=>change("tipoInspecao",e.target.value)}><option value="ANTES_LAVAGEM">Pré-lavagem</option><option value="APOS_LAVAGEM">Pós-lavagem</option></select></label>
          {values.tipoInspecao==="ANTES_LAVAGEM"?<label className="inspection-field"><span>Status inicial</span><select value={values.status} onChange={e=>change("status",e.target.value)}><option value="APROVADO">Aprovado</option><option value="REPROVADO">Reprovado</option><option value="COM_OBSERVACAO">Com observação</option></select></label>:<><label className="inspection-field"><span>Lavador responsável</span><select value={values.colaboradorId} onChange={e=>change("colaboradorId",e.target.value)}><option value="">Selecione</option>{collaborators.map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select></label><label className="inspection-field"><span>Resultado</span><select value={values.resultadoPosLavagem} onChange={e=>change("resultadoPosLavagem",e.target.value)}><option value="">Selecione</option><option>APROVADO</option><option>REPROVADO</option></select></label>{values.resultadoPosLavagem==="REPROVADO"?<label className="inspection-field inspection-field--wide"><span>Motivo da não conformidade</span><select value={values.motivoNaoConformidade} onChange={e=>change("motivoNaoConformidade",e.target.value)}><option value="">Selecione</option>{["FERRUGEM","MANCHA","AMARELAMENTO","ODOR","PRODUTO_RESIDUAL","VALVULA_CONTAMINADA","OUTRO"].map(v=><option key={v}>{v}</option>)}</select></label>:null}</>}
        </div></section>:null}
      {step===1?<section aria-labelledby="step-checklist"><div className="inspection-stage__title"><span>2</span><div><h1 id="step-checklist">Checklist</h1><p>Marque cada ponto como OK ou atenção.</p></div></div><div className="guided-checklist">{checklist.map(item=><article className={`guided-checklist__item ${item.status.toLowerCase()}`} key={item.id}><div><strong>{item.label}</strong><small>{item.localizacao}</small></div><div className="guided-checklist__actions"><button type="button" className={item.status==="OK"?"active-ok":""} onClick={()=>updateChecklist(item.id,"status","OK")}>✓ OK</button><button type="button" className={item.status==="ATENCAO"?"active-warning":""} onClick={()=>updateChecklist(item.id,"status","ATENCAO")}>! Atenção</button></div>{item.status==="ATENCAO"?<div className="guided-checklist__details"><label><span>Categoria</span><select value={item.categoria} onChange={e=>updateChecklist(item.id,"categoria",e.target.value)}>{CATEGORIAS.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Severidade</span><select value={item.severidade} onChange={e=>updateChecklist(item.id,"severidade",e.target.value)}>{SEVERIDADES.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Descrição</span><textarea value={item.descricao} onChange={e=>updateChecklist(item.id,"descricao",e.target.value)}/></label><label><span>Procedimento recomendado</span><textarea value={item.procedimentoRecomendado} onChange={e=>updateChecklist(item.id,"procedimentoRecomendado",e.target.value)}/></label></div>:null}</article>)}</div></section>:null}
      {step===2?<section aria-labelledby="step-evidence"><div className="inspection-stage__title"><span>3</span><div><h1 id="step-evidence">Evidências</h1><p>Registre pontos adicionais, fotos e vídeos.</p></div></div><CriticalPointForm pontosCriticos={pontos} onAdd={addPoint} onUpdate={(index,field,value)=>setPontos(p=>p.map((item,i)=>i===index?{...item,[field]:value}:item))} onRemove={index=>setPontos(p=>p.filter((_,i)=>i!==index))} onChangeFiles={(index,files)=>setPontos(p=>p.map((item,i)=>i===index?{...item,files}:item))} onRemoveFile={(index,fileIndex)=>setPontos(p=>p.map((item,i)=>i===index?{...item,files:item.files.filter((_,fi)=>fi!==fileIndex)}:item))}/><label className="inspection-field review-notes"><span>Observações gerais</span><textarea value={values.observacoesGerais} onChange={e=>change("observacoesGerais",e.target.value)} placeholder="Informações adicionais da inspeção"/></label></section>:null}
      {step===3?<section aria-labelledby="step-review"><div className="inspection-stage__title"><span>4</span><div><h1 id="step-review">Revisão e envio</h1><p>Confira os dados antes de finalizar.</p></div></div><div className="inspection-review"><article><span>Última carga</span><strong>{selectedProduct?.name||"Não informada"}</strong><small>{PROCEDURES[selectedProduct?.washingProcedure||"NOT_DEFINED"]}</small><button type="button" onClick={()=>setStep(0)}>Editar</button></article><article><span>Frota</span><strong>{values.numeroFrota||"Não informada"}</strong><small>{values.placa||"Sem placa"} · {values.tipoEquipamento||"Sem tipo"}</small><button type="button" onClick={()=>setStep(0)}>Editar</button></article><article><span>Checklist</span><strong>{checklist.filter(i=>i.status==="OK").length} OK · {checklist.filter(i=>i.status==="ATENCAO").length} atenção</strong><small>{checklist.filter(i=>i.status==="PENDENTE").length} pendentes</small><button type="button" onClick={()=>setStep(1)}>Editar</button></article><article><span>Evidências</span><strong>{pontos.reduce((n,p)=>n+(p.files?.length||0),0)} arquivos</strong><small>{pontos.length} pontos adicionais</small><button type="button" onClick={()=>setStep(2)}>Editar</button></article></div></section>:null}
    </main><aside className="inspection-summary"><h2>Resumo da inspeção</h2><dl><div><dt>Produto</dt><dd>{selectedProduct?.name||"—"}</dd></div><div><dt>Frota</dt><dd>{values.numeroFrota||"—"}</dd></div><div><dt>Placa</dt><dd>{values.placa||"—"}</dd></div><div><dt>Tanque</dt><dd>{values.tipoEquipamento||"—"}</dd></div><div><dt>Etapa</dt><dd>{STEPS[step]}</dd></div></dl></aside></div>
    <div className="inspection-stage-actions"><button type="button" className="draft-action" onClick={step?()=>setStep(s=>s-1):saveDraft}>{step?"Voltar":"Salvar rascunho"}</button><button type="button" className="continue-action" disabled={saving} onClick={step===3?submit:goNext}>{saving?"Enviando...":step===3?"Finalizar inspeção":"Continuar"}</button></div>
    {productDetails&&selectedProduct?<div className="product-detail-overlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setProductDetails(false)}><section className="inspection-product-drawer" role="dialog" aria-modal="true" aria-labelledby="product-drawer-title"><header><div><small>Detalhes da carga</small><h2 id="product-drawer-title">{selectedProduct.name}</h2></div><button type="button" onClick={()=>setProductDetails(false)} aria-label="Fechar">×</button></header><dl><div><dt>ONU</dt><dd>{selectedProduct.unNumber||"Não informado"}</dd></div><div><dt>Família</dt><dd>{selectedProduct.family?.name||"Não informada"}</dd></div><div><dt>Procedimento</dt><dd>{PROCEDURES[selectedProduct.washingProcedure||"NOT_DEFINED"]}</dd></div><div><dt>Dificuldade</dt><dd>{LEVELS[selectedProduct.washDifficulty]||"Não informada"}</dd></div><div><dt>Risco</dt><dd>{LEVELS[selectedProduct.riskLevel]||"Não informado"}</dd></div><div className="wide"><dt>Observação operacional</dt><dd>{selectedProduct.washingProcedureNotes||"Sem observação."}</dd></div><div className="wide"><dt>Pontos críticos</dt><dd>{selectedProduct.criticalPoints||"Não informados."}</dd></div></dl><Button type="button" onClick={()=>navigate(`/produtos/${selectedProduct.id}`)}>Abrir ficha completa</Button></section></div>:null}
  </div></AppLayout>
}
