import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import AppLayout from "../components/layout/AppLayout"; import AppHeader from "../components/layout/AppHeader"; import Card from "../components/ui/Card"; import Button from "../components/ui/Button";
import { deleteProduct, getProduct, updateProduct } from "../api"; import { isGestor } from "../utils/auth";
const labels = { LOW: "Baixo", MEDIUM: "Médio", HIGH: "Alto" };
const detailFields = [["chemicalName","Nome químico"],["internalCode","Código interno"],["unNumber","Número ONU"],["physicalState","Estado físico"],["color","Cor"],["odor","Odor"],["polarity","Polaridade"],["solubility","Solubilidade"],["flammability","Inflamabilidade"],["corrosivity","Corrosividade"],["toxicity","Toxicidade"],["riskClass","Classe de risco"],["washType","Tipo de lavagem"],["recommendedCleaningProducts","Produtos de limpeza recomendados"],["averageWashMinutes","Tempo médio (minutos)"],["criticalPoints","Pontos críticos"],["residueHidePoints","Onde costuma esconder resíduo"],["mainRejectionCauses","Principais causas de reprovação"],["approvalCriteria","Critérios de aprovação"],["notes","Observações"],["manualVersion","Versão do manual"]];
export default function ProductDetailPage() { const { id } = useParams(); const navigate = useNavigate(); const canManage = isGestor(); const [product,setProduct]=useState(null); const [editing,setEditing]=useState(false); const [form,setForm]=useState({}); const [error,setError]=useState("");
  useEffect(()=>{ getProduct(id).then(({product})=>{setProduct(product);setForm(product);}).catch(e=>setError(e.message)); },[id]);
  async function save(){try{const result=await updateProduct(id,{...form,familyName:form.family?.name,manufacturerName:form.manufacturer?.name,aliases:form.aliases?.map(a=>a.name)});const fresh=await getProduct(result.product.id);setProduct(fresh.product);setForm(fresh.product);setEditing(false);}catch(e){setError(e.message)}}
  async function remove(){if(!window.confirm("Excluir este produto? Produtos já usados serão apenas arquivados."))return;await deleteProduct(id);navigate("/produtos");}
  if(!product)return _jsx(AppLayout,{children:_jsx(Card,{children:error||"Carregando ficha técnica..."})});
  return _jsx(AppLayout,{children:_jsxs("div",{className:"page-stack product-detail",children:[_jsx(AppHeader,{eyebrow:"Ficha técnica do produto",title:product.name,description:`Atualizado em ${new Date(product.updatedAt).toLocaleDateString("pt-BR")}`}),
    _jsxs("section",{className:"product-detail__hero",children:[_jsxs("div",{children:[_jsx("span",{className:"product-flask product-flask--large",children:"⚗"}),_jsxs("div",{children:[_jsx("span",{children:product.family?.name||"Família não informada"}),_jsx("strong",{children:product.manufacturer?.name||"Fabricante não informado"})]})]}),_jsxs("div",{className:"product-detail__badges",children:[_jsx("span",{className:`product-risk product-risk--${product.riskLevel.toLowerCase()}`,children:`Risco ${labels[product.riskLevel]}`}),_jsx("span",{className:`product-risk product-risk--${product.washDifficulty.toLowerCase()}`,children:`Lavagem ${labels[product.washDifficulty]}`}),_jsx("span",{className:"product-risk",children:product.requiresSteam?"Necessita vapor":"Vapor não padrão"})]})]}),
    canManage?_jsxs("div",{className:"detail-actions",children:[_jsx(Button,{variant:"secondary",onClick:()=>setEditing(!editing),children:editing?"Cancelar edição":"Editar produto"}),editing?_jsx(Button,{onClick:save,children:"Salvar alterações"}):null,_jsx(Button,{variant:"danger",onClick:remove,children:"Excluir / arquivar"})]}):null,
    error?_jsx("p",{className:"notice notice--error",children:error}):null,
    _jsx("section",{className:"product-detail__grid",children:detailFields.map(([key,label])=>_jsxs(Card,{className:`product-fact ${["criticalPoints","residueHidePoints","mainRejectionCauses","approvalCriteria","notes"].includes(key)?"product-fact--wide":""}`,children:[_jsx("span",{children:label}),editing?_jsx(key==="notes"||key.includes("Points")||key.includes("Causes")||key==="approvalCriteria"?"textarea":"input",{className:"input",value:form[key]??"",onChange:e=>setForm(c=>({...c,[key]:e.target.value}))}):_jsx("strong",{children:key==="averageWashMinutes"&&product[key]?`${product[key]} min`:product[key]||"Não informado"})]},key))}),
    _jsxs(Card,{children:[_jsx("h2",{className:"section-title",children:"Documentos técnicos"}),product.documents.length?product.documents.map(d=>_jsx("a",{className:"product-document",href:d.fileUrl,target:"_blank",rel:"noreferrer",children:`↗ ${d.fileName}${d.version?` · versão ${d.version}`:""}`},d.id)):_jsx("p",{className:"helper",children:"Nenhum documento associado diretamente. Importações gerais permanecem registradas no histórico."})]}),
    _jsxs(Card,{children:[_jsx("h2",{className:"section-title",children:"Histórico em inspeções"}),product.inspections.length?_jsx("div",{className:"product-history",children:product.inspections.map(i=>_jsxs("button",{onClick:()=>navigate(`/inspecao/${i.inspection.id}`),children:[_jsx("strong",{children:`Frota ${i.inspection.frota.numeroFrota}`}),_jsx("span",{children:new Date(i.inspection.dataInspecao).toLocaleString("pt-BR")}),_jsx("span",{children:i.inspection.status})]},i.id))}):_jsx("p",{className:"helper",children:"Ainda não há inspeções vinculadas a este produto."})]}),
    _jsxs(Card,{children:[_jsx("h2",{className:"section-title",children:"Auditoria de alterações"}),product.history.map(h=>_jsxs("p",{className:"product-audit",children:[_jsx("strong",{children:h.action})," · ",new Date(h.createdAt).toLocaleString("pt-BR")," · ",h.changedBy?.fullName||h.changedBy?.name||"Sistema"]},h.id))]})]})}); }
