import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import AppLayout from "../components/layout/AppLayout"; import AppHeader from "../components/layout/AppHeader"; import Card from "../components/ui/Card"; import Button from "../components/ui/Button";
import { bulkUpdateProductProcedure, getProductDashboard, importProducts, listProducts, previewProductImport } from "../api"; import { isGestor } from "../utils/auth";
const riskLabels={LOW:"Baixo",MEDIUM:"Médio",HIGH:"Alto"};
const procedureLabels={WASH_ONLY:"Lavagem sem vapor",STEAM_ONLY:"Somente vapor",WASH_AND_STEAM:"Lavagem + vapor",NO_WASH_REQUIRED:"Não necessita lavagem",NOT_DEFINED:"Não definido"};
function RiskBadge({value}){return _jsx("span",{className:`product-risk product-risk--${String(value||"LOW").toLowerCase()}`,children:riskLabels[value]??value})}
function ProcedureBadge({value}){const key=value||"NOT_DEFINED";return _jsx("span",{className:`procedure-badge procedure-badge--${key.toLowerCase()}`,children:procedureLabels[key]})}
function Ranking({title,rows,field}){return _jsxs(Card,{className:"product-ranking",children:[_jsx("h3",{children:title}),rows?.length?rows.slice(0,5).map((row,index)=>_jsxs("div",{children:[_jsxs("span",{children:[index+1,". ",row.product.name]}),_jsx("strong",{children:row[field]})]},row.product.id)):_jsx("p",{className:"helper",children:"Sem dados no período."})]})}
export default function ProductsPage(){const navigate=useNavigate(),canManage=isGestor();const[search,setSearch]=useState(""),[familyId,setFamilyId]=useState(""),[risk,setRisk]=useState(""),[procedure,setProcedure]=useState(""),[page,setPage]=useState(1);const[selected,setSelected]=useState([]),[bulkProcedure,setBulkProcedure]=useState("NOT_DEFINED"),[bulkNotes,setBulkNotes]=useState("");const[data,setData]=useState({products:[],families:[],pagination:{page:1,pages:1,total:0}}),[dashboard,setDashboard]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  async function reload(targetPage=page){setData(await listProducts({search,familyId,risk,procedure,page:targetPage}))}
  useEffect(()=>{const timer=setTimeout(()=>reload().catch(e=>setNotice(e.message)),250);return()=>clearTimeout(timer)},[search,familyId,risk,procedure,page]);useEffect(()=>{getProductDashboard().then(setDashboard).catch(()=>null)},[]);
  async function handleImport(event){const file=event.target.files?.[0];if(!file)return;setBusy(true);setNotice("");try{const{preview}=await previewProductImport(file);const changes=preview.filter(r=>r.willChangeProcedure),protectedRows=preview.filter(r=>r.protectedByManualOverride);const details=changes.slice(0,12).map(r=>`${r.name}: ${procedureLabels[r.incomingProcedure]}`).join("\n");if(!window.confirm(`Prévia: ${preview.length} produtos; ${changes.length} procedimentos sugeridos; ${protectedRows.length} decisões manuais protegidas.\n\n${details}${changes.length>12?"\n...":""}\n\nConfirmar importação?`))return;const result=await importProducts(file);setNotice(`Importação concluída: ${result.summary.created} novos, ${result.summary.updated} atualizados. Decisões manuais preservadas.`);setPage(1);await reload(1)}catch(e){setNotice(e.message)}finally{setBusy(false);event.target.value=""}}
  async function applyBulk(){if(!selected.length)return;if(!window.confirm(`${selected.length} produtos receberão “${procedureLabels[bulkProcedure]}”. A decisão manual substituirá sugestões automáticas.`))return;setBusy(true);try{const result=await bulkUpdateProductProcedure(selected,bulkProcedure,bulkNotes);setNotice(`${result.updated} procedimentos atualizados e auditados.`);setSelected([]);await reload();setDashboard(await getProductDashboard())}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function quickUpdate(id,value){setBusy(true);try{await bulkUpdateProductProcedure([id],value,"");await reload()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  const procedureOptions=Object.entries(procedureLabels).map(([value,label])=>_jsx("option",{value,children:label},value));
  return _jsx(AppLayout,{children:_jsxs("div",{className:"page-stack products-page",children:[_jsx(AppHeader,{eyebrow:"Inteligência química",title:"Produtos",description:"Catálogo técnico e procedimentos operacionais reais da estação."}),
    _jsxs("section",{className:"products-hero",children:[_jsxs("div",{children:[_jsx("span",{children:"CATÁLOGO INDUSTRIAL"}),_jsxs("strong",{children:[data.pagination.total," produtos controlados"]}),_jsx("p",{children:"Procedimentos manuais, auditáveis e preservados no histórico."})]}),canManage?_jsxs("label",{className:"button product-import",children:[busy?"Processando...":"Importar PDF ou planilha",_jsx("input",{type:"file",accept:".pdf,.xlsx,.csv",disabled:busy,onChange:handleImport})]}):null]}),notice?_jsx("p",{className:"notice",children:notice}):null,
    _jsxs(Card,{className:"product-search",children:[_jsx("input",{className:"input",value:search,placeholder:"Buscar nome, ONU, fabricante, família ou sinônimo...",onChange:e=>{setSearch(e.target.value);setPage(1)}}),_jsxs("select",{className:"select",value:familyId,onChange:e=>{setFamilyId(e.target.value);setPage(1)},children:[_jsx("option",{value:"",children:"Todas as famílias"}),data.families.map(f=>_jsx("option",{value:f.id,children:f.name},f.id))]}),_jsxs("select",{className:"select",value:risk,onChange:e=>{setRisk(e.target.value);setPage(1)},children:[_jsx("option",{value:"",children:"Todos os riscos"}),_jsx("option",{value:"LOW",children:"Baixo"}),_jsx("option",{value:"MEDIUM",children:"Médio"}),_jsx("option",{value:"HIGH",children:"Alto"})]}),_jsxs("select",{className:"select",value:procedure,onChange:e=>{setProcedure(e.target.value);setPage(1)},children:[_jsx("option",{value:"",children:"Todos os procedimentos"}),...procedureOptions]})]}),
    canManage?_jsxs(Card,{className:"product-bulk",children:[_jsxs("div",{children:[_jsx("strong",{children:"Configurar procedimentos em massa"}),_jsxs("span",{children:[selected.length," produtos selecionados"]})]}),_jsxs("select",{className:"select",value:bulkProcedure,onChange:e=>setBulkProcedure(e.target.value),children:procedureOptions}),_jsx("input",{className:"input",placeholder:"Observação operacional opcional",value:bulkNotes,onChange:e=>setBulkNotes(e.target.value)}),_jsx(Button,{disabled:busy||!selected.length,onClick:applyBulk,children:"Revisar e aplicar"}),_jsx("small",{children:"A configuração manual terá prioridade e será registrada na auditoria."})]}):null,
    _jsx("section",{className:"product-grid",children:data.products.map(p=>_jsxs("article",{className:"product-card",children:[_jsxs("div",{className:"product-card__head",children:[canManage?_jsx("input",{type:"checkbox",checked:selected.includes(p.id),"aria-label":`Selecionar ${p.name}`,onChange:e=>setSelected(c=>e.target.checked?[...c,p.id]:c.filter(id=>id!==p.id))}):_jsx("span",{className:"product-flask",children:"⚗"}),_jsx(RiskBadge,{value:p.riskLevel})]}),_jsx("button",{className:"product-card__open",onClick:()=>navigate(`/produtos/${p.id}`),children:_jsxs("span",{children:[_jsx("h2",{children:p.name}),_jsx("p",{children:p.chemicalName||"Nome químico não informado"})]})}),_jsx(ProcedureBadge,{value:p.washingProcedure}),_jsxs("div",{className:"product-card__meta",children:[_jsx("span",{children:p.family?.name||"Sem família"}),_jsxs("span",{children:["ONU ",p.unNumber||"—"]})]}),canManage?_jsxs("select",{className:"select product-quick-procedure","aria-label":`Procedimento de ${p.name}`,value:p.washingProcedure,onChange:e=>void quickUpdate(p.id,e.target.value),children:procedureOptions}):null,_jsxs("footer",{children:[_jsx("span",{children:p.manufacturer?.name||"Fabricante não informado"}),_jsx("button",{onClick:()=>navigate(`/produtos/${p.id}`),children:"Abrir ficha →"})]})]},p.id))}),
    !data.products.length?_jsx(Card,{children:_jsx("p",{className:"helper",children:"Nenhum produto encontrado."})}):null,_jsxs("div",{className:"product-pagination",children:[_jsx(Button,{variant:"secondary",disabled:page<=1,onClick:()=>setPage(p=>p-1),children:"Anterior"}),_jsxs("span",{children:["Página ",page," de ",Math.max(1,data.pagination.pages)]}),_jsx(Button,{variant:"secondary",disabled:page>=data.pagination.pages,onClick:()=>setPage(p=>p+1),children:"Próxima"})]}),
    dashboard?_jsxs("section",{children:[_jsx("h2",{className:"section-title",children:"Indicadores de procedimento"}),_jsx("div",{className:"procedure-kpis",children:Object.entries(procedureLabels).map(([value,label])=>_jsxs("article",{children:[_jsx("span",{children:label}),_jsx("strong",{children:dashboard.procedureCounts?.[value]??0}),_jsxs("small",{children:[dashboard.inspectionProcedureCounts?.[value]??0," inspeções"]})]},value))}),_jsxs("div",{className:"product-rankings",children:[_jsx(Ranking,{title:"Mais transportados",rows:dashboard.mostTransported,field:"transported"}),_jsx(Ranking,{title:"Mais reprovados",rows:dashboard.mostRejected,field:"rejected"}),_jsx(Ranking,{title:"Maior tempo de lavagem",rows:dashboard.longestWash,field:"averageMinutes"}),_jsx(Ranking,{title:"Maior recorrência",rows:dashboard.mostRecurring,field:"recurrence"})]})]}):null]})})}
